version: '3'
services:
    codeigniter-app:
        build: .
        container_name: expense_manager
        volumes:
            - ./:/var/www/html/
            - ./logs:/var/log/apache2/
        ports:
            - "8082:80"
        restart: always
networks:
    spider_web:
        external: true